# Generated by Django 4.0 on 2021-12-07 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webtoons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webtoons',
            name='img',
            field=models.TextField(),
        ),
    ]
