# Generated by Django 3.2.9 on 2021-12-03 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('feeing', models.CharField(max_length=80)),
                ('score', models.IntegerField()),
                ('dt_created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
            ],
        ),
    ]
